version: '3.7'

services:
  rest:
    build:
      context: .
      dockerfile: .docker/go/dev/Dockerfile
      args:
        install_compile_deamon: "on"
    command: bash -c 'CompileDaemon -log-prefix=false -build="go build -race -o bin/rest ./cmd/rest" -command="./bin/rest -addr :8000" --graceful-kill=true -color=true'
    volumes:
      - type: bind
        source: .
        target: /app
    expose:
      - 8000
    ports:
      - ${REST_PORT}:8000

  grpc-company:
    build:
      context: .
      dockerfile: .docker/go/dev/Dockerfile
      args:
        install_compile_deamon: "on"
      command: bash -c 'CompileDaemon -log-prefix=false -build="go build -race -o bin/company ./cmd/grpc/company" -command="./bin/company -addr :50051" --graceful-kill=true -color=true'
      volumes:
        - type: bind
          source: .
          target: /app
      expose:
        - 50051
      ports:
        - ${GRPC_COMPANY_PORT}:50051

  postgres:
    image: postgres:11.6
    environment:
      - POSTGRES_USER=postgres
    expose:
      - 5432
    ports:
      - ${PG_PORT}:5432
    volumes:
      - pgdata11:/var/lib/postgresql/data

volumes:
  pgdata11:


