// Code generated by protoc-gen-go. DO NOT EDIT.
// source: domain/company/port/grpc/company.proto

package company

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateCompanyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Country              string   `protobuf:"bytes,2,opt,name=country" json:"country,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	City                 string   `protobuf:"bytes,4,opt,name=city" json:"city,omitempty"`
	Street               string   `protobuf:"bytes,5,opt,name=street" json:"street,omitempty"`
	Number               string   `protobuf:"bytes,6,opt,name=number" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyRequest) Reset()         { *m = CreateCompanyRequest{} }
func (m *CreateCompanyRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyRequest) ProtoMessage()    {}
func (*CreateCompanyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_company_7a0bd7ae1ff4e6ef, []int{0}
}
func (m *CreateCompanyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyRequest.Unmarshal(m, b)
}
func (m *CreateCompanyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyRequest.Marshal(b, m, deterministic)
}
func (dst *CreateCompanyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyRequest.Merge(dst, src)
}
func (m *CreateCompanyRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyRequest.Size(m)
}
func (m *CreateCompanyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyRequest proto.InternalMessageInfo

func (m *CreateCompanyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateCompanyRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CreateCompanyRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *CreateCompanyRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *CreateCompanyRequest) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *CreateCompanyRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type CreateCompanyResponse struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateCompanyResponse) Reset()         { *m = CreateCompanyResponse{} }
func (m *CreateCompanyResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCompanyResponse) ProtoMessage()    {}
func (*CreateCompanyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_company_7a0bd7ae1ff4e6ef, []int{1}
}
func (m *CreateCompanyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCompanyResponse.Unmarshal(m, b)
}
func (m *CreateCompanyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCompanyResponse.Marshal(b, m, deterministic)
}
func (dst *CreateCompanyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCompanyResponse.Merge(dst, src)
}
func (m *CreateCompanyResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCompanyResponse.Size(m)
}
func (m *CreateCompanyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCompanyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCompanyResponse proto.InternalMessageInfo

func (m *CreateCompanyResponse) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateCompanyRequest)(nil), "company.createCompanyRequest")
	proto.RegisterType((*CreateCompanyResponse)(nil), "company.createCompanyResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Company service

type CompanyClient interface {
	CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error)
}

type companyClient struct {
	cc *grpc.ClientConn
}

func NewCompanyClient(cc *grpc.ClientConn) CompanyClient {
	return &companyClient{cc}
}

func (c *companyClient) CreateCompany(ctx context.Context, in *CreateCompanyRequest, opts ...grpc.CallOption) (*CreateCompanyResponse, error) {
	out := new(CreateCompanyResponse)
	err := grpc.Invoke(ctx, "/company.company/CreateCompany", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Company service

type CompanyServer interface {
	CreateCompany(context.Context, *CreateCompanyRequest) (*CreateCompanyResponse, error)
}

func RegisterCompanyServer(s *grpc.Server, srv CompanyServer) {
	s.RegisterService(&_Company_serviceDesc, srv)
}

func _Company_CreateCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompanyServer).CreateCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/company.company/CreateCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompanyServer).CreateCompany(ctx, req.(*CreateCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Company_serviceDesc = grpc.ServiceDesc{
	ServiceName: "company.company",
	HandlerType: (*CompanyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCompany",
			Handler:    _Company_CreateCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "domain/company/port/grpc/company.proto",
}

func init() {
	proto.RegisterFile("domain/company/port/grpc/company.proto", fileDescriptor_company_7a0bd7ae1ff4e6ef)
}

var fileDescriptor_company_7a0bd7ae1ff4e6ef = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xcf, 0x4a, 0xc4, 0x30,
	0x10, 0xc6, 0xad, 0xee, 0x76, 0x71, 0xc0, 0xcb, 0xb0, 0x4a, 0x10, 0x14, 0xe9, 0x41, 0x04, 0x61,
	0x0b, 0xfa, 0x08, 0x7d, 0x01, 0xe9, 0xd5, 0x53, 0x9a, 0x0e, 0xd2, 0x43, 0xfe, 0x98, 0x4c, 0x0e,
	0x7d, 0x19, 0x9f, 0x55, 0x92, 0x34, 0x20, 0xa2, 0xb7, 0xef, 0xf7, 0x2b, 0xfd, 0x32, 0x33, 0xf0,
	0x38, 0x5b, 0x2d, 0x17, 0xd3, 0x2b, 0xab, 0x9d, 0x34, 0x6b, 0xef, 0xac, 0xe7, 0xfe, 0xc3, 0x3b,
	0x55, 0xcd, 0xc9, 0x79, 0xcb, 0x16, 0x0f, 0x1b, 0x76, 0x5f, 0x0d, 0x1c, 0x95, 0x27, 0xc9, 0x34,
	0x14, 0x33, 0xd2, 0x67, 0xa4, 0xc0, 0x88, 0xb0, 0x33, 0x52, 0x93, 0x68, 0x1e, 0x9a, 0xa7, 0xcb,
	0x31, 0x67, 0x14, 0x70, 0x50, 0x36, 0x1a, 0xf6, 0xab, 0x38, 0xcf, 0xba, 0x22, 0x1e, 0x61, 0x1f,
	0x58, 0x32, 0x89, 0x8b, 0xec, 0x0b, 0xa4, 0x0e, 0xb5, 0xf0, 0x2a, 0x76, 0xa5, 0x23, 0x65, 0xbc,
	0x81, 0x36, 0xb0, 0x27, 0x62, 0xb1, 0xcf, 0x76, 0xa3, 0xe4, 0x4d, 0xd4, 0x13, 0x79, 0xd1, 0x16,
	0x5f, 0xa8, 0x7b, 0x86, 0xeb, 0x5f, 0xf3, 0x05, 0x67, 0x4d, 0xc8, 0xe5, 0x31, 0x2e, 0x73, 0x1d,
	0x30, 0xe5, 0x97, 0x77, 0xa8, 0x8b, 0xe1, 0x1b, 0x5c, 0x0d, 0x3f, 0xff, 0xc3, 0xbb, 0x53, 0x3d,
	0xc1, 0x5f, 0xfb, 0xde, 0xde, 0xff, 0xf7, 0xb9, 0x3c, 0xd7, 0x9d, 0x4d, 0x6d, 0x3e, 0xdd, 0xeb,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x27, 0x51, 0xf6, 0x64, 0x01, 0x00, 0x00,
}
